lib/dash_web/router.ex
defmodule DashWeb.Router do
  use DashWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :xml do
    plug :accepts, ["xml"]
  end

  scope "/", DashWeb do
    pipe_through :xml

    get "/atom.xml", AtomController, :index
    get "/sitemap.xml", SitemapController, :index
  end

  scope "/#{Application.get_env(:dash, :admin_path)}", DashWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", PostController
  end

  scope "/", DashWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/:permalink", PageController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Dash do
  #   pipe_through :api
  # end
end

lib/dash/blog/post.ex
defmodule Dash.Blog.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias Dash.Blog.Post

  schema "posts" do
    field :title, :string
    field :summary, :string
    field :body, :string
    field :permalink, :string
    field :tags, {:array, :string}
    field :published, :boolean, default: false
    field :published_at, :utc_datetime
    field :tags_text, :string, virtual: true

    belongs_to :user, Dash.Blog.User

    timestamps()
  end

  @doc false
  def changeset(%Post{} = post, attrs) do
    post
    |> cast(attrs, [:title, :body, :permalink, :tags_text, :tags, :summary, :published, :published_at, :user_id])
    |> validate_required([:title])
    |> unique_constraint(:permalink)
    |> inflate_tags
    |> update_published
  end

  def update_published(changeset) do
    case {changeset.changes[:published], changeset.data.published} do
      {true, false} -> put_published_at(changeset)
      _ -> changeset
    end
  end

  def put_published_at(changeset) do
    change(changeset,
      %{published_at: Ecto.DateTime.utc(), published: true})
  end

  def inflate_tags(changeset) do
    case changeset.changes[:tags_text] do
      nil -> changeset
      _ ->
        new_tags = String.split(changeset.params["tags_text"], ",", trim: true)
                    |> Enum.map(&String.trim/1)

        put_change(changeset, :tags, new_tags)
    end
  end

  @doc """
  Flatten a `tags` field into a string separated by comma and sets new
  value on `tags_text` virtual field. `tags` field is
  a Postgresql array.

  If `tags` field is empty, this method sets an empty string.
  """
  def flat_tags(%Post{} = post) do
    flatten = case post.tags do
      [_|_] -> Enum.join(post.tags, ", ")
      _ -> ""
    end

    Map.put(post, :tags_text, flatten)
    post
  end
end

lib/dash_web/controllers/post_controller.ex
defmodule DashWeb.PostController do
  use DashWeb, :controller

  alias Dash.Blog
  alias Dash.Blog.Post

  plug :scrub_params, "post" when action in [:create, :update]

  def index(conn, _params) do
    posts = Blog.list_posts()
    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = Blog.change_post(%Post{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    with {:ok, %Post{} = post} <- Blog.create_post(post_params) do
      conn
      |> put_flash(:info, "Post created successfully.")
      |> redirect(to: post_path(conn, :index))
    else
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    render(conn, "show.html", post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    changeset = Blog.change_post(post)

    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Blog.get_post!(id)

    with {:ok, %Post{} = post} <- Blog.update_post(post, post_params) do
      conn
      |> put_flash(:info, "Post updated successfully.")
      |> redirect(to: post_path(conn, :show, post))
    else
      {:error, changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Blog.get_post!(id)

    with {:ok, %Post{}} <- Blog.delete_post(post) do
      conn
      |> put_flash(:info, "Post deleted successfully.")
      |> redirect(to: post_path(conn, :index))
    end
  end
end

lib/dash_web/views/post_view.ex
defmodule DashWeb.PostView do
  use DashWeb, :view

  import DashWeb.PostHelper

  def published(%{published: true}) do
    "- (published)"
  end

  def published(%{published: false}) do
    ""
  end

  def render("styles.html", assigns) do
    conn = assigns[:conn]
    raw "<link rel='stylesheet' href='#{static_url(conn, "/css/admin.css")}'>"
  end
end

web/templates/post/index.html.eex
<div class='container'>
  <h2>Posts</h2>

  <table class='pure-table pure-table-horizontal'>
    <tbody>
      <%= for post <- @posts do %>
        <tr>
          <td>
            <h3>
              <%= link post.title, to: post_path(@conn, :show, post) %>
              <span><%= published(post) %></span>
            </h3>
            <p class='permalink'><%= page_url(@conn, :show, post.permalink) %></p>
            <p class='tags'><%= flat_tags(post) %></p>
            <p><%= post.summary %></p>
            <div class='actions'>
              <%= link "Edit", to: post_path(@conn, :edit, post), class: "btn btn-default btn-xs" %>
              <%= link "Delete", to: post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

web/templates/post/show.html.eex
<article class='post-view container'>
  <h1><%= @post.title %></h1>
  <span class='author'><%= "By #{author_name(@post.user)}" %></span>
  <span class='time'><%= human_date(@post.published_at) %></span>
  <p class='tags'>
  <% if @post.tags do %>
    <%= for tag <- @post.tags do %>
      <span class='tag'><%= tag %></span>
    <% end %>
  <% end %>
  </p>
  <div class='content'>
    <% if @post.body do %>
      <%= markdown_to_html(@post.body) %>
    <% end %>
    </a>
  </div>
</article>