lib/dash_web/router.ex
defmodule DashWeb.Router do
  use DashWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :xml do
    plug :accepts, ["xml"]
  end

  scope "/", DashWeb do
    pipe_through :xml

    get "/atom.xml", AtomController, :index
    get "/sitemap.xml", SitemapController, :index
  end

  scope "/#{Application.get_env(:dash, :admin_path)}", DashWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", PostController
  end

  scope "/", DashWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/:permalink", PageController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Dash do
  #   pipe_through :api
  # end
end

lib/dash_web/views/layout_view.ex
defmodule DashWeb.LayoutView do
  use DashWeb, :view

  import DashWeb.UrlHelper

  def render_meta(assigns) do
    render_existing(DashWeb.LayoutView, "meta.html", assigns)
  end

  def page_title(_conn, assigns) do
    case assigns[:post] do
      nil -> I18n.t!("en", "seo.title")
      _ -> assigns[:post].title
    end
  end

  def page_description(_conn, assigns) do
    case assigns[:post] do
      nil -> I18n.t!("en", "seo.description")
      _ -> assigns[:post].summary
    end
  end

  def current_page_url(conn, assigns) do
    path = case assigns[:post] do
      nil -> "/"
      _ -> "/" <> assigns[:post].permalink
    end

    static_url(conn, path)
  end

  def is_admin?(conn) do
    case view_module(conn) do
      DashWeb.PostView -> true
      _ -> false
    end
  end

  def add_admin_css_class(conn) do
    case is_admin?(conn) do
      true -> "admin"
      _ -> ""
    end
  end
end

web/templates/layout/meta.html.eex
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="<%= page_description(@conn, assigns) %>">
<meta name="keywords" content="<%= gettext("design, develop, startup, code, ruby, rails, node, javascript, elixir, angularjs, reactjs, ios, android, app, legacy, maintenance, upgrade") %>">
<meta name="author" content="Michelada.io">

<meta property="og:title" content="<%= page_title(@conn, assigns) %>">
<meta property="og:type" content="article">
<meta property="og:image" content="<%= static_url(@conn, "/images/main-logo.png") %>">
<meta property="og:description" content="<%= page_description(@conn, assigns) %>">
<meta property="og:url" content="<%= current_page_url(@conn, assigns) %>">

<meta name="twitter:card" content="summary">
<meta name="twitter:url" content="<%= current_page_url(@conn, assigns) %>">
<meta name="twitter:title" content="<%= page_title(@conn, assigns) %>">
<meta name="twitter:description" content="<%= page_description(@conn, assigns) %>">
<meta name="twitter:image" content="<%= static_url(@conn, "/images/main-logo.png") %>">
<meta name="twitter:site" content="@micheladaio">
<link rel="alternate" type="application/atom+xml" title="feed" href="<%= atom_url(@conn, :index) %>" />

<title>michelada.io :: <%= page_title(@conn, assigns) %></title>